console.log("Infodose conectado", {"ts":1771291932319,"id":"26fbbf40-793d-4a9a-9a44-5d395a462def","meta":{"app":"generated.app"}});
import "./modules/inline-0.js";
import "./modules/inline-1.js";
import "./modules/inline-2.js";
import "./modules/inline-3.js";
import "./modules/inline-4.js";
import "./modules/inline-5.js";
import "./modules/inline-6.js";
import "./modules/inline-7.js";
import "./modules/inline-8.js";
