(function(){
"use strict";
const state = {slices:[],current:0,speaking:false,paused:false,documentTitle:'ESPAÇO DA MENTE',sliceArches:[],raw:'',title:''};
const stage = document.getElementById('sliceStage');
const emptyState = document.getElementById('emptyState');
const fileInput = document.getElementById('fileInput');
const player = document.getElementById('player');
const playButton = document.getElementById('playButton');
const playerTitle = document.getElementById('playerTitle');
const playerState = document.getElementById('playerState');
const progressBar = document.getElementById('progressBar');
const documentTitle = document.getElementById('documentTitle');
if(!stage) return;
const ARCH_SYMBOLS={ATLAS:"α",NOVA:"✦",VITALIS:"♾",PULSE:"◈",ARTEMIS:"☾",SERENA:"❋",KAOS:"⚡",GENUS:"⚙",LUMINE:"☀",SOLUS:"◌",RHEA:"∞",AION:"⧗",KODUX:"⇄",BLLUE:"◉",JESUS:"✝",KOBLLUX:"∆"};
const ARCH_NAMES_SORTED=["KOBLLUX","VITALIS","ARTEMIS","SERENA","LUMINE","KODUX","ATLAS","GENUS","PULSE","JESUS","SOLUS","BLLUE","NOVA","RHEA","KAOS","AION"];
function escapeRegex(s){ return String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
function detectArchInText(raw){if(!raw) return null;const text = String(raw);for(const name of ARCH_NAMES_SORTED){const sym = ARCH_SYMBOLS[name];if(!sym) continue;const reSym = new RegExp(escapeRegex(sym) + "\\s*[·:\\-—]?\\s*" + name + "\\b", "i");if(reSym.test(text)) return name;}for(const name of ARCH_NAMES_SORTED){const reHead = new RegExp("^#{1,6}\\s*" + escapeRegex(name) + "\\b", "im");if(reHead.test(text)) return name;}for(const name of ARCH_NAMES_SORTED){const reLead = new RegExp("^" + escapeRegex(name) + "\\s*[·:\\-—]\\s", "im");if(reLead.test(text)) return name;}for(const name of ARCH_NAMES_SORTED){const reWord = new RegExp("\\b" + escapeRegex(name) + "\\b", "i");if(reWord.test(text)) return name;}return null;}
function archColor(name){const map = window.ARCH_MAP;if(!map || !map[name]) return "var(--kob-voice-primary)";return `var(${map[name].tok})`;}
function buildSliceArches(slices){return slices.map(raw => detectArchInText(raw));}
function openFile(){ fileInput.click(); }
function pasteText(){const text = prompt('Cole aqui o texto:');if(!text) return;loadDocument(text, 'Documento colado');}
function parseDocument(text){const lines = text.replace(/\r/g,'').split('\n');const slices = []; let current = [];function push(){ const v=current.join('\n').trim(); if(v) slices.push(v); current=[]; }for(const line of lines){if(/^#{1,3}\s+/.test(line)){ if(current.length) push(); current.push(line); continue; }if(/^---+$/.test(line.trim())){ push(); continue; }current.push(line);}if(current.length) push();if(slices.length <= 1){const blocks = text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);if(blocks.length > 1) return blocks;}return slices;}
function escapeHTML(text){return text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function markdownToHTML(text){let html = escapeHTML(text);html = html.replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>');html = html.replace(/^### (.*)$/gm,'<h3>$1</h3>');html = html.replace(/^## (.*)$/gm,'<h2>$1</h2>');html = html.replace(/^# (.*)$/gm,'<h1>$1</h1>');html = html.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>');html = html.replace(/\*(.*?)\*/g,'<em>$1</em>');html = html.replace(/_([^_]+)_/g,'<em>$1</em>');html = html.replace(/`([^`]+)`/g,'<code>$1</code>');html = html.replace(/^&gt; (.*)$/gm,'<blockquote>$1</blockquote>');html = html.split(/\n\s*\n/).map(block=>{block = block.trim(); if(!block) return '';if(/^<(h1|h2|h3|ul|pre|blockquote)/.test(block)) return block;return `<p>${block.replace(/\n/g,'<br>')}</p>`;}).join('');return html;}
function createSlice(content, index){const s = document.createElement('slice');const detected = state.sliceArches[index];const isAuto = !detected;const arch = detected || (window.getArch && window.getArch()) || 'JESUS';const color = archColor(arch);s.dataset.index = index; s.dataset.state = 'created'; s.dataset.arch = arch; s.dataset.auto = isAuto ? "1" : "0";s.style.setProperty("--slice-arch-color", color);s.innerHTML = `<div class="slice-content"><div class="slice-meta"><label>SLICE ${String(index+1).padStart(2,'0')}</label><span class="slice-arch-chip ${isAuto ? 'auto' : ''}"><i></i>${isAuto ? '◆ AUTO' : arch}</span><span class="slice-number">${index+1} / ${state.slices.length}</span></div><div class="slice-body">${markdownToHTML(content)}</div></div>`;return s;}
function loadDocument(text, title){stopSpeech();state.raw = text; state.title = title||'Documento';state.slices = parseDocument(text);state.current = 0;state.documentTitle = title || 'Documento';state.sliceArches = buildSliceArches(state.slices);if(documentTitle) documentTitle.textContent = state.documentTitle;if(playerTitle) playerTitle.textContent = state.documentTitle;stage.replaceChildren();state.slices.forEach((c,i)=>stage.appendChild(createSlice(c,i)));if(emptyState) emptyState.style.display = state.slices.length ? 'none' : 'grid';showSlice(0);if(window.KBLX_SAVE) window.KBLX_SAVE();}
function showSlice(index){if(!state.slices.length) return;if(index < 0) index = state.slices.length - 1;if(index >= state.slices.length) index = 0;state.current = index;stage.querySelectorAll('slice').forEach((s,i)=>{s.classList.toggle('active', i === index);});if(progressBar) progressBar.style.width = `${((index + 1) / state.slices.length) * 100}%`;const detected = state.sliceArches[index];const arch = detected || (window.getArch && window.getArch()) || 'JESUS';if(playerState) playerState.textContent = detected ? `Slice ${index + 1}/${state.slices.length} · ${detected}` : `Slice ${index + 1}/${state.slices.length} · ${arch} (auto)`;if(state.speaking) speakCurrentSlice();}
function nextSlice(){ if(!state.slices.length) return; if(state.current < state.slices.length - 1) showSlice(state.current + 1); else stopSpeech(); }
function previousSlice(){ if(!state.slices.length) return; showSlice(state.current - 1); }
function getCurrentText(){const s = state.slices[state.current]; if(!s) return '';return s.replace(/```[\s\S]*?```/g,' código ').replace(/^#{1,6}\s+/gm,'').replace(/[*_~`]/g,'').replace(/^>\s*/gm,'').replace(/^[-*]\s+/gm,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/\n+/g,' ').trim();}
function speakCurrentSlice(){if(!('speechSynthesis' in window)){ if(playerState) playerState.textContent = 'Speech indisponível'; return; }speechSynthesis.cancel();const text = getCurrentText(); if(!text) return;const detected = state.sliceArches[state.current];const archName = detected || (window.getArch && window.getArch()) || 'JESUS';if(window.applyArch) window.applyArch(archName);if(window.__sbSync) window.__sbSync(archName);const u = new SpeechSynthesisUtterance(text);if(window.KBLX_VOICE && window.KBLX_VOICE.forArch){const cfg = window.KBLX_VOICE.forArch(archName, text);if(cfg.voice) u.voice = cfg.voice;u.lang = cfg.lang || 'pt-BR'; u.rate = cfg.rate || 1; u.pitch = cfg.pitch || 1;}u.onstart = ()=>{state.speaking = true; state.paused = false; if(playButton) playButton.textContent = 'Ⅱ'; if(playerState) playerState.textContent = `🎙 ${archName} · slice ${state.current + 1}`; const orb = document.getElementById('sbOrb'); if(orb) orb.classList.add('speaking');};u.onend = ()=>{if(state.speaking){if(state.current < state.slices.length - 1){ state.current++; showSlice(state.current); } else stopSpeech();}};u.onerror = ()=>{state.speaking = false; if(playButton) playButton.textContent = '▶'; const orb = document.getElementById('sbOrb'); if(orb) orb.classList.remove('speaking');};speechSynthesis.speak(u);}
function toggleSpeech(){if(!state.slices.length) return;if(state.speaking){if(speechSynthesis.paused){ speechSynthesis.resume(); state.paused = false; if(playButton) playButton.textContent = 'Ⅱ'; return; }speechSynthesis.pause(); state.paused = true; if(playButton) playButton.textContent = '▶'; if(playerState) playerState.textContent = 'Pausado';return;}state.speaking = true; speakCurrentSlice();}
function stopSpeech(){if('speechSynthesis' in window) speechSynthesis.cancel();state.speaking = false; state.paused = false;if(playButton) playButton.textContent = '▶';const orb = document.getElementById('sbOrb'); if(orb) orb.classList.remove('speaking');}
function togglePlayer(){ player.classList.toggle('minimized'); }
function clear(){state.slices=[]; state.current=0; state.sliceArches=[]; state.raw=''; state.title=''; stopSpeech(); stage.replaceChildren(); if(emptyState) emptyState.style.display='grid'; if(playerTitle) playerTitle.textContent='Nenhum'; if(playerState) playerState.textContent='Aguardando'; if(progressBar) progressBar.style.width='0%';}
function hasSlices(){ return state.slices.length > 0; }
fileInput.addEventListener('change', async event => {const f = event.target.files[0]; if(!f) return; const txt = await f.text(); loadDocument(txt, f.name);});
document.addEventListener('keydown', event => {if(event.target.matches('textarea,input,[contenteditable="true"]')) return;if(event.key === 'ArrowRight') nextSlice();if(event.key === 'ArrowLeft') previousSlice();});
let touchStartX = 0;
document.addEventListener('touchstart', e => { touchStartX = e.changedTouches[0].screenX; }, {passive:true});
document.addEventListener('touchend', e => {const diff = e.changedTouches[0].screenX - touchStartX;if(Math.abs(diff) < 80) return;if(!e.target.closest('#readerApp')) return;if(diff < 0) nextSlice(); else previousSlice();}, {passive:true});
window.Nebula = {openFile, pasteText, loadDocument, showSlice, nextSlice, previousSlice, toggleSpeech, stopSpeech, togglePlayer, clear, hasSlices, state, detectArchInText};
})();